### ISSUE TITLE
ImportError: No module named settings

### ISSUE THREAD

**Issue by seongbae** [fictive-kin/openrecipes#215]
Hi,

When I run "scrapy list", I get "ImportError: No module named settings" error.  Have you guys seen this before?  I'm using scrapy 1.1.2, python 2.7.3.

Thank you.

```
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 9, in <module>
    load_entry_point('Scrapy==1.1.2', 'console_scripts', 'scrapy')()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 282, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings
```

**Comment by funkatron** [comment]
I think you want to make a copy of this file, removing the `.default` extension. https://github.com/fictivekin/openrecipes/blob/master/scrapy_proj/openrecipes/settings.py.default

**Comment by seongbae** [comment]
I did that already but placed the settings.py file in scrapy_proj folder.  I moved it to scrapy_proj/openrecipes/ and I'm good now. Thanks!
