### ISSUE TITLE
AttributeError: 'list' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by seongbae** [fictive-kin/openrecipes#216]
Hi @funkatron ,

I was following the steps on this page - https://github.com/fictivekin/openrecipes/wiki - and when I run "scrapy crawl thepioneerwoman.feed", I get following error(s).  Do you know why I'm getting this..?  Thank you.

```
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 9, in <module>
    load_entry_point('Scrapy==1.1.2', 'console_scripts', 'scrapy')()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 91, in __init__
    self.update(values, priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'
```

**Comment by seongbae** [comment]
The ITEM_PIPELINE has to be a dictionary.   So in settings.py, change the ITEM_PIPELINE code to following and you shouldn't get the error:

ITEM_PIPELINES = {
    'openrecipes.pipelines.RejectinvalidPipeline': 300,
    'openrecipes.pipelines.DuplicaterecipePipeline': 800,
    # this will insert results into MongoDB
    'openrecipes.pipelines.MongoDBPipeline': 900,
}
